CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  raw JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS ingestion_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  cursor TEXT NULL,
  page INTEGER NOT NULL DEFAULT 0,
  ingested_count BIGINT NOT NULL DEFAULT 0,
  last_ts_ms BIGINT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE ingestion_state
ADD COLUMN IF NOT EXISTS last_ts_ms BIGINT NULL;

INSERT INTO ingestion_state (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;