CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  occurred_at TIMESTAMPTZ NULL,
  received_at TIMESTAMPTZ NULL,
  raw JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS ingestion_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  cursor TEXT NULL,
  page INTEGER NOT NULL DEFAULT 0,
  ingested_count BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO ingestion_state (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;